### ISSUE TITLE
Can not get the entities show up

### ISSUE THREAD

**Issue by f3rr311** [jdeath/Hubspace-Homeassistant#14]
So I have used hacks to add the repository and then added the following:
from what I understood I do not need the Rooms added, I can not see the entities and there are no log entries about the issue 

```
light:
  - platform: hubspace
    username: myEmail
    password: MyPass
    debug: True
    friendlynames:
      - 'Master'
```

**Comment by f3rr311** [comment]
```
2022-11-23 20:50:40.124 DEBUG (SyncWorker_7) [custom_components.hubspace.hubspace] ############ End Dump #########
2022-11-23 20:50:41.265 ERROR (MainThread) [homeassistant.components.light] hubspace: Error on device update!
```

**Comment by f3rr311** [comment]
```
2022-11-23 20:50:22.121 DEBUG (SyncWorker_6) [custom_components.hubspace.light] Switch on Model TBD
2022-11-23 20:50:22.122 DEBUG (SyncWorker_6) [custom_components.hubspace.light] childId: 005a4d41-5020-487b-bc41-c81a7aaac40b
2022-11-23 20:50:22.122 DEBUG (SyncWorker_6) [custom_components.hubspace.light] deviceId: 85a05443b23472aa
2022-11-23 20:50:22.122 DEBUG (SyncWorker_6) [custom_components.hubspace.light] deviceClass: switch
2022-11-23 20:50:22.123 DEBUG (SyncWorker_6) [custom_components.hubspace.light] creating lights
2022-11-23 20:50:22.123 DEBUG (SyncWorker_6) [custom_components.hubspace.light] Light Name: 
2022-11-23 20:50:22.123 DEBUG (SyncWorker_6) [custom_components.hubspace.light] Master
```

**Comment by f3rr311** [comment]
Its named Master in the App, I am changing it now, it does not seem to actually be adding the device into HA

**Comment by f3rr311** [comment]
```
2022-11-23 20:59:06.112 ERROR (MainThread) [homeassistant.components.light] hubspace: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 336, in update
    self._brightness = _brightness_to_hass(self._hs.getState(self._childId,"brightness"))
  File "/config/custom_components/hubspace/light.py", line 54, in _brightness_to_hass
    return int(value) * 255 // 100
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2022-11-23 20:59:18.939 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /ingress/session request
2022-11-23 20:59:18.945 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /ingress/session - 
```

**Comment by jdeath** [comment]
Hmm. What is your model? Looks like it doesn't support brightness or there is a bug.

I think the default assumes a light and looks like your model is a switch I have not seen yet. I need the model string, it should be in the attributes of light.master (or whatever you named it)

**Comment by f3rr311** [comment]
https://www.homedepot.com/p/Commercial-Electric-Smart-Hubspace-10-Amp-Single-Pole-Specialty-Light-Switch-with-Wi-Fi-and-Bluetooth-Technology-White-1-Pack-HPSA11CWB/320313682#overlay

**Comment by jdeath** [comment]
Ok. Give me 5 minutes I'll push a new release

**Comment by f3rr311** [comment]
They are on sale for like $15 so I figured I would test them out, honestly don't worry till after the holiday.

**Comment by jdeath** [comment]
No worries. Just needed to add the model. I guessed from the home depot listing. Let me know if v1.6 works. May need to refresh hacs

**Comment by f3rr311** [comment]
```
2022-11-23 21:27:25.827 ERROR (MainThread) [homeassistant.components.light] Error while setting up hubspace platform for light
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7ab4b2b0>: Failed to establish a new connection: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='accounts.hubspaceconnect.com', port=443): Max retries exceeded with url: /auth/realms/thd/protocol/openid-connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7ab4b2b0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 110, in setup_platform
    hs = HubSpace(username,password)
  File "/config/custom_components/hubspace/hubspace.py", line 28, in __init__
    self._refresh_token = self.getRefreshCode()
  File "/config/custom_components/hubspace/hubspace.py", line 109, in getRefreshCode
    r = requests.post(auth_url, data=auth_data, headers=auth_header)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='accounts.hubspaceconnect.com', port=443): Max retries exceeded with url: /auth/realms/thd/protocol/openid-connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7ab4b2b0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

```

**Comment by f3rr311** [comment]
I think I hit an API limit

**Comment by jdeath** [comment]
hmm. Maybe you tried too many times to restart the integration. Comment out the light configuration and restart. In a few hours, remove the comment and restart. Hopefully it will work in a couple hours

**Comment by f3rr311** [comment]
Tried a reload and it loaded and added the entity, THANK you so much for the integration and hard work

**Comment by jdeath** [comment]
awesome. Glad it is working
