### ISSUE TITLE
devices are not responding

### ISSUE THREAD

**Issue by djqpaz** [jdeath/Hubspace-Homeassistant#5]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/95603822/176594717-6f414a50-efed-47d0-871e-d693d35145cc.png">

see these logs

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/hubspace/hubspace.py:286
Integration: hubspace (documentation)
First occurred: June 27, 2022, 12:28:35 PM (1 occurrences)
Last logged: June 27, 2022, 12:28:35 PM

Update for light.officetv_outlet_1 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 310, in update
    self._debugInfo = self._hs.getDebugInfo(self._childId)
  File "/config/custom_components/hubspace/hubspace.py", line 286, in getDebugInfo
    _LOGGER.debug(json.dumps(r.json(), indent=4, sort_keys=True))
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/hubspace/hubspace.py:296
Integration: hubspace (documentation)
First occurred: June 27, 2022, 6:22:15 AM (107 occurrences)
Last logged: June 27, 2022, 8:04:46 AM

Update for light.entryway fails
Update for light.guest_bath fails
Update for light.officetv fails
Update for light.master_closet fails
Update for light.testoutlet_outlet_1 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 220, in update
    self._debugInfo = self._hs.getDebugInfo(self._childId)
  File "/config/custom_components/hubspace/hubspace.py", line 296, in getDebugInfo
    _LOGGER.debug(json.dumps(r.json(), indent=4, sort_keys=True))
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

**Comment by jdeath** [comment]
Try turning debug: false in your configuration.yaml and let's see if that avoids the error . Mine is working. Looks like the API might be returning bad data and I do not check for it. Also looks like the API went down for a bit as well, but seems to be up now.

**Comment by djqpaz** [comment]
Will do, I'll let you know if I see something again.
