### ISSUE TITLE
Error while setting up hubspace platform for light

### ISSUE THREAD

**Issue by flyingtech** [jdeath/Hubspace-Homeassistant#60]
I'm very new to home assistant so not sure what is happening.  I did enter my username and password in the /config/configuration.yaml but I didn't add the friendly names and removed those lines.

I do see my 2 PIR switch entities in home assistant but I can't control them. i gett the following pop up:
![image](https://github.com/jdeath/Hubspace-Homeassistant/assets/14594149/8c6de438-e537-49b1-8918-49d0ef89d396)

I set logging to true but I don't know where to get that log.  bellow is from the settings/systems/Logs menu after restarting HA:

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:359
Integration: Light (documentation, issues)
First occurred: 1:22:00 PM (1 occurrences)
Last logged: 1:22:00 PM

Error while setting up hubspace platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hubspace/light.py", line 128, in setup_platform
    hs = HubSpace(username, password)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hubspace/hubspace.py", line 29, in __init__
    self._refresh_token = self.getRefreshCode()
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hubspace/hubspace.py", line 103, in getRefreshCode
    session_state = re.search("session_state=(.+?)&code", location).group(1)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/re/__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

**Comment by flyingtech** [comment]
Ok, the API must have been down when I was setting it up. I tried it again and its working as expected.

Thank you for the help.
