### ISSUE TITLE
Color changes stopped working with 1.0 release

### ISSUE THREAD

**Issue by waseltzer** [jdeath/Hubspace-Homeassistant#89]
Just updated to Hubspace 3.0.
I have one light “538551010, 538561010, 538552010, 538562010
by Commercial Electric.”
It had been working fine with the previous release.
With the new release, on, off, and dim are working.
However, color changes result in errors like:
“Failed to call service light/turn_on. 500, message=‘Internal Server Error’, url=URL(‘https://api2.afero.net/v1/accounts/f4bd2419-f74b-4977-a6f8-32c65d807f54/metadevices/bce7759c-2955-4c27-ad81-6aa56aa80025/state’)”

The Hubspace app on Android is able to change colors.

In the log:
`2024-08-01 10:43:21.187 INFO (MainThread) [custom_components.hubspace.light] Adjusting light bce7759c-2955-4c27-ad81-6aa56aa80025 with {'rgb_color': (255, 163, 232)}
2024-08-01 10:43:21.187 DEBUG (MainThread) [hubspace_async.connection] Update the device [bce7759c-2955-4c27-ad81-6aa56aa80025] with new states: [HubSpaceState(functionClass='power', value='on', lastUpdateTime=None, functionInstance=None), HubSpaceState(functionClass='color-rgb', value=(255, 163, 232), lastUpdateTime=None, functionInstance=None)]
2024-08-01 10:43:21.283 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547442754176] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/hubspace/light.py", line 452, in async_turn_on
    await self._hs.set_device_states(self._child_id, states_to_set)
  File "/usr/local/lib/python3.12/site-packages/hubspace_async/connection.py", line 252, in set_device_states
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api2.afero.net/v1/accounts/f4bd2419-f74b-4977-a6f8-32c65d807f54/metadevices/bce7759c-2955-4c27-ad81-6aa56aa80025/state')
2024-08-01 10:43:21.428 INFO (MainThread) [custom_components.hubspace.light] Adjusting light bce7759c-2955-4c27-ad81-6aa56aa80025 with {'rgb_color': (224, 178, 255)}
2024-08-01 10:43:21.429 DEBUG (MainThread) [hubspace_async.connection] Update the device [bce7759c-2955-4c27-ad81-6aa56aa80025] with new states: [HubSpaceState(functionClass='power', value='on', lastUpdateTime=None, functionInstance=None), HubSpaceState(functionClass='color-rgb', value=(224, 178, 255), lastUpdateTime=None, functionInstance=None)]
2024-08-01 10:43:21.463 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547442754176] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/hubspace/light.py", line 452, in async_turn_on
    await self._hs.set_device_states(self._child_id, states_to_set)
  File "/usr/local/lib/python3.12/site-packages/hubspace_async/connection.py", line 252, in set_device_states
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api2.afero.net/v1/accounts/f4bd2419-f74b-4977-a6f8-32c65d807f54/metadevices/bce7759c-2955-4c27-ad81-6aa56aa80025/state')
2024-08-01 10:43:21.692 INFO (MainThread) [custom_components.hubspace.light] Adjusting light bce7759c-2955-4c27-ad81-6aa56aa80025 with {'rgb_color': (224, 178, 255)}
2024-08-01 10:43:21.692 DEBUG (MainThread) [hubspace_async.connection] Update the device [bce7759c-2955-4c27-ad81-6aa56aa80025] with new states: [HubSpaceState(functionClass='power', value='on', lastUpdateTime=None, functionInstance=None), HubSpaceState(functionClass='color-rgb', value=(224, 178, 255), lastUpdateTime=None, functionInstance=None)]
2024-08-01 10:43:21.726 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547442754176] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/hubspace/light.py", line 452, in async_turn_on
    await self._hs.set_device_states(self._child_id, states_to_set)
  File "/usr/local/lib/python3.12/site-packages/hubspace_async/connection.py", line 252, in set_device_states
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api2.afero.net/v1/accounts/f4bd2419-f74b-4977-a6f8-32c65d807f54/metadevices/bce7759c-2955-4c27-ad81-6aa56aa80025/state')
2024-08-01 10:43:25.503 DEBUG (MainThread) [hubspace_async.connection] Querying API for all data
2024-08-01 10:43:25.578 DEBUG (MainThread) [hubspace_async.connection] Adding a new home, 239e6d1c-9c2c-412e-965a-e45b52b21e4f
2024-08-01 10:43:25.578 DEBUG (MainThread) [hubspace_async.connection] Unable to process a result of type metadevice.home
2024-08-01 10:43:25.579 DEBUG (MainThread) [hubspace_async.connection] Adding a new room, 9df77b81-8e42-4e1a-8393-626504e735c1
2024-08-01 10:43:25.579 DEBUG (MainThread) [hubspace_async.connection] Adding a new device, bce7759c-2955-4c27-ad81-6aa56aa80025
2024-08-01 10:43:25.580 DEBUG (MainThread) [custom_components.hubspace.discovery] Performing auto discovery
2024-08-01 10:43:25.580 INFO (MainThread) [custom_components.hubspace.discovery] Performing discovery for the following friendly names: Basement office ceiling
2024-08-01 10:43:25.587 DEBUG (MainThread) [custom_components.hubspace.coordinator] Writing out anonymized device data to /config/custom_components/hubspace/_dump_hs_devices.json
2024-08-01 10:43:26.557 DEBUG (MainThread) [custom_components.hubspace.coordinator] Writing out raw device data to /config/custom_components/hubspace/_dump_hs_raw.json
2024-08-01 10:43:26.573 DEBUG (MainThread) [custom_components.hubspace.coordinator] Adding device Basement office ceiling to light
2024-08-01 10:43:26.574 DEBUG (MainThread) [custom_components.hubspace.coordinator] Finished fetching hubspace data in 1.073 seconds (success: True)`

**Comment by waseltzer** [comment]
[v3.0](https://github.com/jdeath/Hubspace-Homeassistant/releases/tag/v3.0)

**Comment by Expl0dingBanana** [comment]
Thanks for this info! I believe this issue is the same as #58 after 3.0.

**Comment by Expl0dingBanana** [comment]
I believe this has been fixed with #91 . Please review the testing instructions within that PR and post any comments within that PR.

**Comment by waseltzer** [comment]
Installed v3.0.2 following the testing instructions in PR [#91](https://github.com/jdeath/Hubspace-Homeassistant/pull/91).
RGB changes are working now.
Thanks!
